### PR TITLE
redesigned error handling

### PR DESCRIPTION
**Pull request by Bannsaenger**
I added the ability to use a own error handler in the parent application.

The background is, that i use the library together with Node-RED. If you throw the error in the 
library, the application exits because you cannot catch these error in Node-RED.

### CODE REVIEW

**Comment by margau** [comment]
Hi,
sorry for the delay.
To be honest, I'm currently not actively working with dmxnet, due to time constraints and other projects.
In general, this looks good - thanks!
Can you remove the package.json changes from the PR, or are they strictly needed for this feature?

I think we can merge it then.

**Comment by Bannsaenger** [comment]
I removed the package* files from the PR.
The changes from @kev-ac  are merged and i added the esat code in the type script definition as well.
Hope this is all right now to merge my PR

**Comment by Bannsaenger** [comment]
Ok, i synced my files with these from margau repository.

**Comment by kev-ac** [comment]
I've created a separate PR in #54 to remove the confusing commits of removal and adding of package files. 
Please feel free to review it.

**Comment by margau** [comment]
Closed in #55

**Pull request closed without merging**
