### PR TITLE
Add TypeScript definition

### PR DESCRIPTION
**Pull request by she11sh0cked**
Useful for us TypeScript folk

### CODE REVIEW

**Comment by margau** [comment]
Hi,
thanks for the PR. Seems good on the first look, will have a more detailed on in the next days.

Could you squash your commits into a single one?
Thanks!

**Comment by she11sh0cked** [comment]
This should be ok right? :)

**Comment by she11sh0cked** [comment]
@margau Is there anything missing here?

**Comment by margau** [comment]
Sorry, was busy this week.
Need to deploy some more automation over here. Will release soon.

**Pull request merged**
